### PR TITLE
[WORKING] Forward calls to kubectl

### PR DESCRIPTION
**Pull request by ucirello**

### CODE REVIEW

**Comment by ucirello** [comment]
// cc @gerred 

> Comment by gerred
> This all looks really good to me. I wasn't yet sold on the wrapper idea, but I'm so far :+1:
> 
> The only thing I'm still really worried about is the tool breaking independently of kubectl, if kubectl is updated on someone's system and we haven't pushed a new kube-cluster binary. At least if we bring kubectl in-house (by adding kubernetes/kubernetes as a dependency and requiring the relevant files), we don't run into that problem.
> 
> I guess since it's a pass through it won't matter.

I think it is a very important aspect - we might need to make a decision about it. 

I see these alternatives:

1 - don't worry, because we are just passing it through as it is - so it will never affect the end-user as long as he knows what he is doing.

2 - we can protect against not-yet-validated versions. Like tying kube-cluster version X with kubectl version Y. And refusing to run unless they match.

What do you think?

**Comment by gerred** [comment]
Some more options, inspired by how docker-machine and docker works:
1. Don't pass through or wrap, rather bake kubectl into kube-cluster. Then version X of kubectl is baked directly into version Y of kube-cluster, and we cut new releases when new Kubernetes API versions come out.
2. Make the tools independent of each other. The downside with this is, honestly, kubectl is a REALLY hard to find tool, and I think makes it harder to get started. Presently, even `brew install kubernetes-cli` breaks for me on Go 1.5 w/ OSX 10.11.

**Comment by ucirello** [comment]
> 1. Don't pass through or wrap, rather bake kubectl into kube-cluster. Then version X of kubectl is baked directly into version Y of kube-cluster, and we cut new releases when new Kubernetes API versions come out.

I think this is a go-to move for the near future, ie. baking each one of the calls into kube-cluster. The wrapper idea is to provide a head start towards this goal. So we can start using kube-cluster right away.

edit: can't -> can

**Comment by gerred** [comment]
Makes sense to me. :+1:

**Comment by ucirello** [comment]
@gerred let's merge? :+1:

**Comment by gerred** [comment]
Merged.

**Pull request merged**
